services:
  server:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8020:8020
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://k.chubarava:12345@db:5432/postgres
    command: bash -c "alembic upgrade head && python src/main.py"

  db:
    image: ankane/pgvector:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-k.chubarava}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

volumes:
  db-data:
